#!/usr/bin/env python3
"""Analyze a captured syslog sample.

Stdlib only. Called from bin/elk-listen analyze.

Output:
  - JSON summary to stdout (parsed by the bash caller)
  - A starter Logstash pipeline conf to OUT_CONF if specified

Heuristics:
  - Detect RFC3164 ("<PRI>Mmm DD HH:MM:SS host app: msg") vs
    RFC5424 ("<PRI>1 ISO8601 host app PROC MSGID STRUCTURED-DATA msg")
  - Pull priority -> facility/severity
  - Suggest grok pattern based on detected format
  - Surface common key=value pairs found in the message body
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path


RE_RFC5424 = re.compile(
    r"^<(?P<pri>\d{1,3})>1\s+"
    r"(?P<ts>\S+)\s+"
    r"(?P<host>\S+)\s+"
    r"(?P<app>\S+)\s+"
    r"(?P<procid>\S+)\s+"
    r"(?P<msgid>\S+)\s+"
    r"(?P<sd>(\[[^\]]*\]\s*)+|-)\s*"
    r"(?P<msg>.*)$"
)

# RFC3164 — the spec uses `TAG: CONTENT` but real-world implementations
# (Barracuda, F5, Cisco, etc.) often omit the colon. We make it optional.
RE_RFC3164 = re.compile(
    r"^<(?P<pri>\d{1,3})>"
    r"(?P<ts>[A-Z][a-z]{2}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})\s+"
    r"(?P<host>\S+)\s+"
    r"(?P<app>[^\[:\s]+)(?:\[(?P<pid>\d+)\])?:?\s*"
    r"(?P<msg>.*)$"
)

# Loose key=value extraction. Matches both bare and quoted values.
RE_KV = re.compile(r"""(?P<k>[A-Za-z_][A-Za-z0-9_.-]{1,40})=(?P<v>"[^"]*"|\S+)""")


def classify(line: str) -> tuple[str, dict | None]:
    """Return (format_name, parsed_groupdict_or_None)."""
    m = RE_RFC5424.match(line)
    if m:
        return ("rfc5424", m.groupdict())
    m = RE_RFC3164.match(line)
    if m:
        return ("rfc3164", m.groupdict())
    return ("unknown", None)


def summarize(sample_path: Path) -> dict:
    lines = [ln.rstrip("\r\n") for ln in sample_path.read_text(errors="replace").splitlines()]
    nonblank = [ln for ln in lines if ln.strip()]

    fmts: Counter[str] = Counter()
    apps: Counter[str] = Counter()
    hosts: Counter[str] = Counter()
    kv_keys: Counter[str] = Counter()
    msg_samples: list[str] = []
    parsed_examples: list[dict] = []

    for ln in nonblank:
        fmt, parsed = classify(ln)
        fmts[fmt] += 1
        if parsed:
            apps[parsed.get("app", "")] += 1
            hosts[parsed.get("host", "")] += 1
            for m in RE_KV.finditer(parsed.get("msg", "")):
                kv_keys[m.group("k")] += 1
            if len(parsed_examples) < 3:
                parsed_examples.append(parsed)
        if len(msg_samples) < 5:
            msg_samples.append(ln[:200])

    return {
        "total_lines": len(lines),
        "nonblank_lines": len(nonblank),
        "format_distribution": dict(fmts),
        "top_apps": apps.most_common(5),
        "top_hosts": hosts.most_common(5),
        "top_kv_keys": kv_keys.most_common(15),
        "msg_samples": msg_samples,
        "parsed_examples": parsed_examples,
    }


GROK_BASE_RFC3164 = "%{SYSLOGLINE}"
GROK_BASE_RFC5424 = (
    "<%{NONNEGINT:[log][syslog][priority]:int}>%{NONNEGINT:[log][syslog][version]:int}"
    " %{TIMESTAMP_ISO8601:[timestamp]}"
    " %{HOSTNAME:[host][name]}"
    " %{DATA:[process][name]}"
    " %{DATA:[process][pid]}"
    " %{DATA:[event][code]}"
    " %{GREEDYDATA:[message_extracted]}"
)


def build_pipeline(vendor: str, summary: dict, internal_port: int) -> str:
    fmts = summary["format_distribution"]
    primary = max(fmts, key=fmts.get) if fmts else "unknown"
    if primary == "rfc5424":
        grok = GROK_BASE_RFC5424
    elif primary == "rfc3164":
        grok = GROK_BASE_RFC3164
    else:
        grok = '%{GREEDYDATA:[message_body]}'

    top_kv = [k for (k, _) in summary["top_kv_keys"][:10]]
    kv_filter = ""
    if top_kv:
        kv_filter = (
            "\n  # Frequent key=value pairs found in samples; auto-extracted.\n"
            "  kv {\n"
            '    field_split_pattern => "[ \\t]"\n'
            '    value_split => "="\n'
            '    include_keys => ["%s"]\n'
            '    target => "[vendor]"\n'
            "  }\n"
        ) % '","'.join(top_kv)

    return f"""# {vendor} pipeline — generated by elk-listen analyze.
# Detected primary syslog format: {primary}
# Top apps:  {summary['top_apps']}
# Top hosts: {summary['top_hosts']}
#
# Iterate this until events parse as expected, then:
#   elk-listen test    pipelines/{vendor}.conf
#   elk-listen promote pipelines/{vendor}.conf --vendor {vendor} \\
#       --external-port <port> --internal-port {internal_port}
#
# When the result is right, freeze it as a template:
#   elk-template export --name {vendor} --version 0.1.0 \\
#       --object dashboard:<id>
#
input {{
  tcp {{
    port => {internal_port}
    codec => line
    type => "{vendor}"
    tags => ["{vendor}", "elk-listen-promoted"]
  }}
}}

filter {{
  grok {{
    match => {{ "message" => "{grok}" }}
    tag_on_failure => ["_grokparsefailure", "_{vendor}_parse_fail"]
  }}{kv_filter}
  date {{
    match => [ "timestamp",
               "ISO8601",
               "MMM  d HH:mm:ss",
               "MMM dd HH:mm:ss" ]
    remove_field => ["timestamp"]
  }}
}}

output {{
  elasticsearch {{
    hosts => ["https://127.0.0.1:9200"]
    user  => "logstash_internal"
    password => "${{LS_ES_PASSWORD}}"
    ssl_certificate_authorities => ["/etc/logstash/certs/elasticsearch-http-ca.crt"]
    data_stream => "true"
    data_stream_type      => "logs"
    data_stream_dataset   => "{vendor.replace('-', '.')}"
    data_stream_namespace => "default"
  }}
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Analyze a captured syslog sample")
    ap.add_argument("sample", type=Path, help="Path to captured sample file")
    ap.add_argument("--vendor", help="Vendor name; if set, also writes a starter pipeline")
    ap.add_argument("--out-conf", type=Path, help="Where to write the starter pipeline (default: pipelines/<vendor>.conf)")
    ap.add_argument("--internal-port", type=int, default=5044,
                    help="Internal LS pipeline port to use in the generated conf (default: 5044)")
    ap.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent,
                    help="Repo root, used to resolve default --out-conf")
    args = ap.parse_args()

    if not args.sample.is_file():
        print(f"error: sample not found: {args.sample}", file=sys.stderr)
        return 2

    summary = summarize(args.sample)
    print(json.dumps(summary, indent=2, default=str))

    if args.vendor:
        conf = build_pipeline(args.vendor, summary, args.internal_port)
        out = args.out_conf or (args.repo_root / "pipelines" / f"{args.vendor}.conf")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(conf)
        print(f"\n# wrote starter pipeline to {out}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
